name: Lint

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  buildifier:
    runs-on: ubuntu-22.04
    env:
      BUILDIFIER_VERSION: v8.2.1

    steps:
      - uses: actions/checkout@v4

      - name: Install buildifier
        run: |
          sudo wget https://github.com/bazelbuild/buildtools/releases/download/${{ env.BUILDIFIER_VERSION }}/buildifier-linux-amd64 -O /usr/local/bin/buildifier
          sudo chmod +x /usr/local/bin/buildifier

      - name: Check formatting
        run: buildifier -lint=warn -mode=check -warnings=all -r .
